[tools]
  erlang = "latest"
  elixir = "latest"
  nodejs = "latest"
  "npm:@fsouza/prettierd" = "latest"
  "npm:@openai/codex" = "latest"
  "npm:bibletui" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
